package com.test.yanxiu.im_core.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImMqtt.proto

public final class ImMqttProto {
  private ImMqttProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImMqttOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImMqtt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 imEvent = 1;</code>
     */
    int getImEvent();

    /**
     * <code>string reqId = 2;</code>
     */
    java.lang.String getReqId();
    /**
     * <code>string reqId = 2;</code>
     */
    com.google.protobuf.ByteString
        getReqIdBytes();

    /**
     * <code>repeated bytes body = 3;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getBodyList();
    /**
     * <code>repeated bytes body = 3;</code>
     */
    int getBodyCount();
    /**
     * <code>repeated bytes body = 3;</code>
     */
    com.google.protobuf.ByteString getBody(int index);
  }
  /**
   * Protobuf type {@code ImMqtt}
   */
  public  static final class ImMqtt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImMqtt)
      ImMqttOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImMqtt.newBuilder() to construct.
    private ImMqtt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImMqtt() {
      imEvent_ = 0;
      reqId_ = "";
      body_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImMqtt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              imEvent_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              reqId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                body_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              body_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          body_ = java.util.Collections.unmodifiableList(body_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImMqttProto.internal_static_ImMqtt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImMqttProto.internal_static_ImMqtt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImMqttProto.ImMqtt.class, ImMqttProto.ImMqtt.Builder.class);
    }

    private int bitField0_;
    public static final int IMEVENT_FIELD_NUMBER = 1;
    private int imEvent_;
    /**
     * <code>int32 imEvent = 1;</code>
     */
    public int getImEvent() {
      return imEvent_;
    }

    public static final int REQID_FIELD_NUMBER = 2;
    private volatile java.lang.Object reqId_;
    /**
     * <code>string reqId = 2;</code>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      }
    }
    /**
     * <code>string reqId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> body_;
    /**
     * <code>repeated bytes body = 3;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getBodyList() {
      return body_;
    }
    /**
     * <code>repeated bytes body = 3;</code>
     */
    public int getBodyCount() {
      return body_.size();
    }
    /**
     * <code>repeated bytes body = 3;</code>
     */
    public com.google.protobuf.ByteString getBody(int index) {
      return body_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (imEvent_ != 0) {
        output.writeInt32(1, imEvent_);
      }
      if (!getReqIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reqId_);
      }
      for (int i = 0; i < body_.size(); i++) {
        output.writeBytes(3, body_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (imEvent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, imEvent_);
      }
      if (!getReqIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reqId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < body_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(body_.get(i));
        }
        size += dataSize;
        size += 1 * getBodyList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImMqttProto.ImMqtt)) {
        return super.equals(obj);
      }
      ImMqttProto.ImMqtt other = (ImMqttProto.ImMqtt) obj;

      boolean result = true;
      result = result && (getImEvent()
          == other.getImEvent());
      result = result && getReqId()
          .equals(other.getReqId());
      result = result && getBodyList()
          .equals(other.getBodyList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMEVENT_FIELD_NUMBER;
      hash = (53 * hash) + getImEvent();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId().hashCode();
      if (getBodyCount() > 0) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBodyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImMqttProto.ImMqtt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImMqttProto.ImMqtt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImMqttProto.ImMqtt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImMqttProto.ImMqtt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImMqttProto.ImMqtt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImMqttProto.ImMqtt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImMqttProto.ImMqtt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImMqttProto.ImMqtt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImMqttProto.ImMqtt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImMqttProto.ImMqtt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImMqttProto.ImMqtt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImMqttProto.ImMqtt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImMqttProto.ImMqtt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImMqtt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImMqtt)
        ImMqttProto.ImMqttOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImMqttProto.internal_static_ImMqtt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImMqttProto.internal_static_ImMqtt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImMqttProto.ImMqtt.class, ImMqttProto.ImMqtt.Builder.class);
      }

      // Construct using ImMqttProto.ImMqtt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        imEvent_ = 0;

        reqId_ = "";

        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImMqttProto.internal_static_ImMqtt_descriptor;
      }

      public ImMqttProto.ImMqtt getDefaultInstanceForType() {
        return ImMqttProto.ImMqtt.getDefaultInstance();
      }

      public ImMqttProto.ImMqtt build() {
        ImMqttProto.ImMqtt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ImMqttProto.ImMqtt buildPartial() {
        ImMqttProto.ImMqtt result = new ImMqttProto.ImMqtt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.imEvent_ = imEvent_;
        result.reqId_ = reqId_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          body_ = java.util.Collections.unmodifiableList(body_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImMqttProto.ImMqtt) {
          return mergeFrom((ImMqttProto.ImMqtt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImMqttProto.ImMqtt other) {
        if (other == ImMqttProto.ImMqtt.getDefaultInstance()) return this;
        if (other.getImEvent() != 0) {
          setImEvent(other.getImEvent());
        }
        if (!other.getReqId().isEmpty()) {
          reqId_ = other.reqId_;
          onChanged();
        }
        if (!other.body_.isEmpty()) {
          if (body_.isEmpty()) {
            body_ = other.body_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBodyIsMutable();
            body_.addAll(other.body_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ImMqttProto.ImMqtt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ImMqttProto.ImMqtt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int imEvent_ ;
      /**
       * <code>int32 imEvent = 1;</code>
       */
      public int getImEvent() {
        return imEvent_;
      }
      /**
       * <code>int32 imEvent = 1;</code>
       */
      public Builder setImEvent(int value) {
        
        imEvent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 imEvent = 1;</code>
       */
      public Builder clearImEvent() {
        
        imEvent_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reqId_ = "";
      /**
       * <code>string reqId = 2;</code>
       */
      public java.lang.String getReqId() {
        java.lang.Object ref = reqId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reqId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReqIdBytes() {
        java.lang.Object ref = reqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqId = 2;</code>
       */
      public Builder setReqId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reqId = 2;</code>
       */
      public Builder clearReqId() {
        
        reqId_ = getDefaultInstance().getReqId();
        onChanged();
        return this;
      }
      /**
       * <code>string reqId = 2;</code>
       */
      public Builder setReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> body_ = java.util.Collections.emptyList();
      private void ensureBodyIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          body_ = new java.util.ArrayList<com.google.protobuf.ByteString>(body_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes body = 3;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getBodyList() {
        return java.util.Collections.unmodifiableList(body_);
      }
      /**
       * <code>repeated bytes body = 3;</code>
       */
      public int getBodyCount() {
        return body_.size();
      }
      /**
       * <code>repeated bytes body = 3;</code>
       */
      public com.google.protobuf.ByteString getBody(int index) {
        return body_.get(index);
      }
      /**
       * <code>repeated bytes body = 3;</code>
       */
      public Builder setBody(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBodyIsMutable();
        body_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes body = 3;</code>
       */
      public Builder addBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBodyIsMutable();
        body_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes body = 3;</code>
       */
      public Builder addAllBody(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureBodyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, body_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes body = 3;</code>
       */
      public Builder clearBody() {
        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImMqtt)
    }

    // @@protoc_insertion_point(class_scope:ImMqtt)
    private static final ImMqttProto.ImMqtt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImMqttProto.ImMqtt();
    }

    public static ImMqttProto.ImMqtt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImMqtt>
        PARSER = new com.google.protobuf.AbstractParser<ImMqtt>() {
      public ImMqtt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImMqtt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImMqtt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImMqtt> getParserForType() {
      return PARSER;
    }

    public ImMqttProto.ImMqtt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMqtt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMqtt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ImMqtt.proto\"6\n\006ImMqtt\022\017\n\007imEvent\030\001 \001(" +
      "\005\022\r\n\005reqId\030\002 \001(\t\022\014\n\004body\030\003 \003(\014B\rB\013ImMqtt" +
      "Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ImMqtt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImMqtt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMqtt_descriptor,
        new java.lang.String[] { "ImEvent", "ReqId", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
