package com.test.yanxiu.im_core.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopicMsg.proto

public final class TopicMsgProto {
  private TopicMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TopicMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TopicMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>int32 bizSource = 2;</code>
     */
    int getBizSource();

    /**
     * <code>int64 topicId = 3;</code>
     */
    long getTopicId();

    /**
     * <code>int64 senderId = 4;</code>
     */
    long getSenderId();

    /**
     * <code>string senderName = 5;</code>
     */
    java.lang.String getSenderName();
    /**
     * <code>string senderName = 5;</code>
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>string reqId = 6;</code>
     */
    java.lang.String getReqId();
    /**
     * <code>string reqId = 6;</code>
     */
    com.google.protobuf.ByteString
        getReqIdBytes();

    /**
     * <code>int32 contentType = 7;</code>
     */
    int getContentType();

    /**
     * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
     */
    boolean hasContentData();
    /**
     * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
     */
    TopicMsgProto.TopicMsg.ContentDataProto getContentData();
    /**
     * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
     */
    TopicMsgProto.TopicMsg.ContentDataProtoOrBuilder getContentDataOrBuilder();

    /**
     * <code>int64 sendTime = 9;</code>
     */
    long getSendTime();
  }
  /**
   * Protobuf type {@code TopicMsg}
   */
  public  static final class TopicMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TopicMsg)
      TopicMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopicMsg.newBuilder() to construct.
    private TopicMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopicMsg() {
      id_ = 0L;
      bizSource_ = 0;
      topicId_ = 0L;
      senderId_ = 0L;
      senderName_ = "";
      reqId_ = "";
      contentType_ = 0;
      sendTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TopicMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              bizSource_ = input.readInt32();
              break;
            }
            case 24: {

              topicId_ = input.readInt64();
              break;
            }
            case 32: {

              senderId_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              reqId_ = s;
              break;
            }
            case 56: {

              contentType_ = input.readInt32();
              break;
            }
            case 66: {
              TopicMsgProto.TopicMsg.ContentDataProto.Builder subBuilder = null;
              if (contentData_ != null) {
                subBuilder = contentData_.toBuilder();
              }
              contentData_ = input.readMessage(TopicMsgProto.TopicMsg.ContentDataProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(contentData_);
                contentData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 72: {

              sendTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TopicMsgProto.internal_static_TopicMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TopicMsgProto.internal_static_TopicMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TopicMsgProto.TopicMsg.class, TopicMsgProto.TopicMsg.Builder.class);
    }

    public interface ContentDataProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TopicMsg.ContentDataProto)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string msg = 1;</code>
       */
      java.lang.String getMsg();
      /**
       * <code>string msg = 1;</code>
       */
      com.google.protobuf.ByteString
          getMsgBytes();

      /**
       * <code>string rid = 2;</code>
       */
      java.lang.String getRid();
      /**
       * <code>string rid = 2;</code>
       */
      com.google.protobuf.ByteString
          getRidBytes();

      /**
       * <code>string thumbnail = 3;</code>
       */
      java.lang.String getThumbnail();
      /**
       * <code>string thumbnail = 3;</code>
       */
      com.google.protobuf.ByteString
          getThumbnailBytes();

      /**
       * <code>string viewUrl = 4;</code>
       */
      java.lang.String getViewUrl();
      /**
       * <code>string viewUrl = 4;</code>
       */
      com.google.protobuf.ByteString
          getViewUrlBytes();

      /**
       * <code>int32 width = 5;</code>
       */
      int getWidth();

      /**
       * <code>int32 height = 6;</code>
       */
      int getHeight();
    }
    /**
     * Protobuf type {@code TopicMsg.ContentDataProto}
     */
    public  static final class ContentDataProto extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:TopicMsg.ContentDataProto)
        ContentDataProtoOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ContentDataProto.newBuilder() to construct.
      private ContentDataProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ContentDataProto() {
        msg_ = "";
        rid_ = "";
        thumbnail_ = "";
        viewUrl_ = "";
        width_ = 0;
        height_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ContentDataProto(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                msg_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                rid_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                thumbnail_ = s;
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                viewUrl_ = s;
                break;
              }
              case 40: {

                width_ = input.readInt32();
                break;
              }
              case 48: {

                height_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TopicMsgProto.internal_static_TopicMsg_ContentDataProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TopicMsgProto.internal_static_TopicMsg_ContentDataProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TopicMsgProto.TopicMsg.ContentDataProto.class, TopicMsgProto.TopicMsg.ContentDataProto.Builder.class);
      }

      public static final int MSG_FIELD_NUMBER = 1;
      private volatile java.lang.Object msg_;
      /**
       * <code>string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        }
      }
      /**
       * <code>string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int RID_FIELD_NUMBER = 2;
      private volatile java.lang.Object rid_;
      /**
       * <code>string rid = 2;</code>
       */
      public java.lang.String getRid() {
        java.lang.Object ref = rid_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rid_ = s;
          return s;
        }
      }
      /**
       * <code>string rid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRidBytes() {
        java.lang.Object ref = rid_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int THUMBNAIL_FIELD_NUMBER = 3;
      private volatile java.lang.Object thumbnail_;
      /**
       * <code>string thumbnail = 3;</code>
       */
      public java.lang.String getThumbnail() {
        java.lang.Object ref = thumbnail_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          thumbnail_ = s;
          return s;
        }
      }
      /**
       * <code>string thumbnail = 3;</code>
       */
      public com.google.protobuf.ByteString
          getThumbnailBytes() {
        java.lang.Object ref = thumbnail_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thumbnail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VIEWURL_FIELD_NUMBER = 4;
      private volatile java.lang.Object viewUrl_;
      /**
       * <code>string viewUrl = 4;</code>
       */
      public java.lang.String getViewUrl() {
        java.lang.Object ref = viewUrl_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          viewUrl_ = s;
          return s;
        }
      }
      /**
       * <code>string viewUrl = 4;</code>
       */
      public com.google.protobuf.ByteString
          getViewUrlBytes() {
        java.lang.Object ref = viewUrl_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          viewUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int WIDTH_FIELD_NUMBER = 5;
      private int width_;
      /**
       * <code>int32 width = 5;</code>
       */
      public int getWidth() {
        return width_;
      }

      public static final int HEIGHT_FIELD_NUMBER = 6;
      private int height_;
      /**
       * <code>int32 height = 6;</code>
       */
      public int getHeight() {
        return height_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getMsgBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
        }
        if (!getRidBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rid_);
        }
        if (!getThumbnailBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, thumbnail_);
        }
        if (!getViewUrlBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, viewUrl_);
        }
        if (width_ != 0) {
          output.writeInt32(5, width_);
        }
        if (height_ != 0) {
          output.writeInt32(6, height_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getMsgBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
        }
        if (!getRidBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rid_);
        }
        if (!getThumbnailBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, thumbnail_);
        }
        if (!getViewUrlBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, viewUrl_);
        }
        if (width_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, width_);
        }
        if (height_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, height_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof TopicMsgProto.TopicMsg.ContentDataProto)) {
          return super.equals(obj);
        }
        TopicMsgProto.TopicMsg.ContentDataProto other = (TopicMsgProto.TopicMsg.ContentDataProto) obj;

        boolean result = true;
        result = result && getMsg()
            .equals(other.getMsg());
        result = result && getRid()
            .equals(other.getRid());
        result = result && getThumbnail()
            .equals(other.getThumbnail());
        result = result && getViewUrl()
            .equals(other.getViewUrl());
        result = result && (getWidth()
            == other.getWidth());
        result = result && (getHeight()
            == other.getHeight());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        hash = (37 * hash) + RID_FIELD_NUMBER;
        hash = (53 * hash) + getRid().hashCode();
        hash = (37 * hash) + THUMBNAIL_FIELD_NUMBER;
        hash = (53 * hash) + getThumbnail().hashCode();
        hash = (37 * hash) + VIEWURL_FIELD_NUMBER;
        hash = (53 * hash) + getViewUrl().hashCode();
        hash = (37 * hash) + WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getWidth();
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static TopicMsgProto.TopicMsg.ContentDataProto parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(TopicMsgProto.TopicMsg.ContentDataProto prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code TopicMsg.ContentDataProto}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:TopicMsg.ContentDataProto)
          TopicMsgProto.TopicMsg.ContentDataProtoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return TopicMsgProto.internal_static_TopicMsg_ContentDataProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return TopicMsgProto.internal_static_TopicMsg_ContentDataProto_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  TopicMsgProto.TopicMsg.ContentDataProto.class, TopicMsgProto.TopicMsg.ContentDataProto.Builder.class);
        }

        // Construct using TopicMsgProto.TopicMsg.ContentDataProto.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          msg_ = "";

          rid_ = "";

          thumbnail_ = "";

          viewUrl_ = "";

          width_ = 0;

          height_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return TopicMsgProto.internal_static_TopicMsg_ContentDataProto_descriptor;
        }

        public TopicMsgProto.TopicMsg.ContentDataProto getDefaultInstanceForType() {
          return TopicMsgProto.TopicMsg.ContentDataProto.getDefaultInstance();
        }

        public TopicMsgProto.TopicMsg.ContentDataProto build() {
          TopicMsgProto.TopicMsg.ContentDataProto result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public TopicMsgProto.TopicMsg.ContentDataProto buildPartial() {
          TopicMsgProto.TopicMsg.ContentDataProto result = new TopicMsgProto.TopicMsg.ContentDataProto(this);
          result.msg_ = msg_;
          result.rid_ = rid_;
          result.thumbnail_ = thumbnail_;
          result.viewUrl_ = viewUrl_;
          result.width_ = width_;
          result.height_ = height_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof TopicMsgProto.TopicMsg.ContentDataProto) {
            return mergeFrom((TopicMsgProto.TopicMsg.ContentDataProto)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(TopicMsgProto.TopicMsg.ContentDataProto other) {
          if (other == TopicMsgProto.TopicMsg.ContentDataProto.getDefaultInstance()) return this;
          if (!other.getMsg().isEmpty()) {
            msg_ = other.msg_;
            onChanged();
          }
          if (!other.getRid().isEmpty()) {
            rid_ = other.rid_;
            onChanged();
          }
          if (!other.getThumbnail().isEmpty()) {
            thumbnail_ = other.thumbnail_;
            onChanged();
          }
          if (!other.getViewUrl().isEmpty()) {
            viewUrl_ = other.viewUrl_;
            onChanged();
          }
          if (other.getWidth() != 0) {
            setWidth(other.getWidth());
          }
          if (other.getHeight() != 0) {
            setHeight(other.getHeight());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          TopicMsgProto.TopicMsg.ContentDataProto parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (TopicMsgProto.TopicMsg.ContentDataProto) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object msg_ = "";
        /**
         * <code>string msg = 1;</code>
         */
        public java.lang.String getMsg() {
          java.lang.Object ref = msg_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            msg_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string msg = 1;</code>
         */
        public com.google.protobuf.ByteString
            getMsgBytes() {
          java.lang.Object ref = msg_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            msg_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string msg = 1;</code>
         */
        public Builder setMsg(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          msg_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string msg = 1;</code>
         */
        public Builder clearMsg() {
          
          msg_ = getDefaultInstance().getMsg();
          onChanged();
          return this;
        }
        /**
         * <code>string msg = 1;</code>
         */
        public Builder setMsgBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          msg_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object rid_ = "";
        /**
         * <code>string rid = 2;</code>
         */
        public java.lang.String getRid() {
          java.lang.Object ref = rid_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            rid_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string rid = 2;</code>
         */
        public com.google.protobuf.ByteString
            getRidBytes() {
          java.lang.Object ref = rid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            rid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string rid = 2;</code>
         */
        public Builder setRid(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          rid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string rid = 2;</code>
         */
        public Builder clearRid() {
          
          rid_ = getDefaultInstance().getRid();
          onChanged();
          return this;
        }
        /**
         * <code>string rid = 2;</code>
         */
        public Builder setRidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          rid_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object thumbnail_ = "";
        /**
         * <code>string thumbnail = 3;</code>
         */
        public java.lang.String getThumbnail() {
          java.lang.Object ref = thumbnail_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            thumbnail_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string thumbnail = 3;</code>
         */
        public com.google.protobuf.ByteString
            getThumbnailBytes() {
          java.lang.Object ref = thumbnail_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            thumbnail_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string thumbnail = 3;</code>
         */
        public Builder setThumbnail(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          thumbnail_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string thumbnail = 3;</code>
         */
        public Builder clearThumbnail() {
          
          thumbnail_ = getDefaultInstance().getThumbnail();
          onChanged();
          return this;
        }
        /**
         * <code>string thumbnail = 3;</code>
         */
        public Builder setThumbnailBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          thumbnail_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object viewUrl_ = "";
        /**
         * <code>string viewUrl = 4;</code>
         */
        public java.lang.String getViewUrl() {
          java.lang.Object ref = viewUrl_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            viewUrl_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string viewUrl = 4;</code>
         */
        public com.google.protobuf.ByteString
            getViewUrlBytes() {
          java.lang.Object ref = viewUrl_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            viewUrl_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string viewUrl = 4;</code>
         */
        public Builder setViewUrl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          viewUrl_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string viewUrl = 4;</code>
         */
        public Builder clearViewUrl() {
          
          viewUrl_ = getDefaultInstance().getViewUrl();
          onChanged();
          return this;
        }
        /**
         * <code>string viewUrl = 4;</code>
         */
        public Builder setViewUrlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          viewUrl_ = value;
          onChanged();
          return this;
        }

        private int width_ ;
        /**
         * <code>int32 width = 5;</code>
         */
        public int getWidth() {
          return width_;
        }
        /**
         * <code>int32 width = 5;</code>
         */
        public Builder setWidth(int value) {
          
          width_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 width = 5;</code>
         */
        public Builder clearWidth() {
          
          width_ = 0;
          onChanged();
          return this;
        }

        private int height_ ;
        /**
         * <code>int32 height = 6;</code>
         */
        public int getHeight() {
          return height_;
        }
        /**
         * <code>int32 height = 6;</code>
         */
        public Builder setHeight(int value) {
          
          height_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 height = 6;</code>
         */
        public Builder clearHeight() {
          
          height_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:TopicMsg.ContentDataProto)
      }

      // @@protoc_insertion_point(class_scope:TopicMsg.ContentDataProto)
      private static final TopicMsgProto.TopicMsg.ContentDataProto DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new TopicMsgProto.TopicMsg.ContentDataProto();
      }

      public static TopicMsgProto.TopicMsg.ContentDataProto getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ContentDataProto>
          PARSER = new com.google.protobuf.AbstractParser<ContentDataProto>() {
        public ContentDataProto parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ContentDataProto(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ContentDataProto> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ContentDataProto> getParserForType() {
        return PARSER;
      }

      public TopicMsgProto.TopicMsg.ContentDataProto getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int BIZSOURCE_FIELD_NUMBER = 2;
    private int bizSource_;
    /**
     * <code>int32 bizSource = 2;</code>
     */
    public int getBizSource() {
      return bizSource_;
    }

    public static final int TOPICID_FIELD_NUMBER = 3;
    private long topicId_;
    /**
     * <code>int64 topicId = 3;</code>
     */
    public long getTopicId() {
      return topicId_;
    }

    public static final int SENDERID_FIELD_NUMBER = 4;
    private long senderId_;
    /**
     * <code>int64 senderId = 4;</code>
     */
    public long getSenderId() {
      return senderId_;
    }

    public static final int SENDERNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object senderName_;
    /**
     * <code>string senderName = 5;</code>
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <code>string senderName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQID_FIELD_NUMBER = 6;
    private volatile java.lang.Object reqId_;
    /**
     * <code>string reqId = 6;</code>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      }
    }
    /**
     * <code>string reqId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 7;
    private int contentType_;
    /**
     * <code>int32 contentType = 7;</code>
     */
    public int getContentType() {
      return contentType_;
    }

    public static final int CONTENTDATA_FIELD_NUMBER = 8;
    private TopicMsgProto.TopicMsg.ContentDataProto contentData_;
    /**
     * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
     */
    public boolean hasContentData() {
      return contentData_ != null;
    }
    /**
     * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
     */
    public TopicMsgProto.TopicMsg.ContentDataProto getContentData() {
      return contentData_ == null ? TopicMsgProto.TopicMsg.ContentDataProto.getDefaultInstance() : contentData_;
    }
    /**
     * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
     */
    public TopicMsgProto.TopicMsg.ContentDataProtoOrBuilder getContentDataOrBuilder() {
      return getContentData();
    }

    public static final int SENDTIME_FIELD_NUMBER = 9;
    private long sendTime_;
    /**
     * <code>int64 sendTime = 9;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (bizSource_ != 0) {
        output.writeInt32(2, bizSource_);
      }
      if (topicId_ != 0L) {
        output.writeInt64(3, topicId_);
      }
      if (senderId_ != 0L) {
        output.writeInt64(4, senderId_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, senderName_);
      }
      if (!getReqIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, reqId_);
      }
      if (contentType_ != 0) {
        output.writeInt32(7, contentType_);
      }
      if (contentData_ != null) {
        output.writeMessage(8, getContentData());
      }
      if (sendTime_ != 0L) {
        output.writeInt64(9, sendTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (bizSource_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bizSource_);
      }
      if (topicId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, topicId_);
      }
      if (senderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, senderId_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, senderName_);
      }
      if (!getReqIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, reqId_);
      }
      if (contentType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, contentType_);
      }
      if (contentData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getContentData());
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, sendTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TopicMsgProto.TopicMsg)) {
        return super.equals(obj);
      }
      TopicMsgProto.TopicMsg other = (TopicMsgProto.TopicMsg) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getBizSource()
          == other.getBizSource());
      result = result && (getTopicId()
          == other.getTopicId());
      result = result && (getSenderId()
          == other.getSenderId());
      result = result && getSenderName()
          .equals(other.getSenderName());
      result = result && getReqId()
          .equals(other.getReqId());
      result = result && (getContentType()
          == other.getContentType());
      result = result && (hasContentData() == other.hasContentData());
      if (hasContentData()) {
        result = result && getContentData()
            .equals(other.getContentData());
      }
      result = result && (getSendTime()
          == other.getSendTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + BIZSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getBizSource();
      hash = (37 * hash) + TOPICID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTopicId());
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSenderId());
      hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId().hashCode();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContentType();
      if (hasContentData()) {
        hash = (37 * hash) + CONTENTDATA_FIELD_NUMBER;
        hash = (53 * hash) + getContentData().hashCode();
      }
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TopicMsgProto.TopicMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopicMsgProto.TopicMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopicMsgProto.TopicMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopicMsgProto.TopicMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopicMsgProto.TopicMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopicMsgProto.TopicMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopicMsgProto.TopicMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TopicMsgProto.TopicMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TopicMsgProto.TopicMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TopicMsgProto.TopicMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TopicMsgProto.TopicMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TopicMsgProto.TopicMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TopicMsgProto.TopicMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TopicMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TopicMsg)
        TopicMsgProto.TopicMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TopicMsgProto.internal_static_TopicMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TopicMsgProto.internal_static_TopicMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TopicMsgProto.TopicMsg.class, TopicMsgProto.TopicMsg.Builder.class);
      }

      // Construct using TopicMsgProto.TopicMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        bizSource_ = 0;

        topicId_ = 0L;

        senderId_ = 0L;

        senderName_ = "";

        reqId_ = "";

        contentType_ = 0;

        if (contentDataBuilder_ == null) {
          contentData_ = null;
        } else {
          contentData_ = null;
          contentDataBuilder_ = null;
        }
        sendTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TopicMsgProto.internal_static_TopicMsg_descriptor;
      }

      public TopicMsgProto.TopicMsg getDefaultInstanceForType() {
        return TopicMsgProto.TopicMsg.getDefaultInstance();
      }

      public TopicMsgProto.TopicMsg build() {
        TopicMsgProto.TopicMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TopicMsgProto.TopicMsg buildPartial() {
        TopicMsgProto.TopicMsg result = new TopicMsgProto.TopicMsg(this);
        result.id_ = id_;
        result.bizSource_ = bizSource_;
        result.topicId_ = topicId_;
        result.senderId_ = senderId_;
        result.senderName_ = senderName_;
        result.reqId_ = reqId_;
        result.contentType_ = contentType_;
        if (contentDataBuilder_ == null) {
          result.contentData_ = contentData_;
        } else {
          result.contentData_ = contentDataBuilder_.build();
        }
        result.sendTime_ = sendTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TopicMsgProto.TopicMsg) {
          return mergeFrom((TopicMsgProto.TopicMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TopicMsgProto.TopicMsg other) {
        if (other == TopicMsgProto.TopicMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getBizSource() != 0) {
          setBizSource(other.getBizSource());
        }
        if (other.getTopicId() != 0L) {
          setTopicId(other.getTopicId());
        }
        if (other.getSenderId() != 0L) {
          setSenderId(other.getSenderId());
        }
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getReqId().isEmpty()) {
          reqId_ = other.reqId_;
          onChanged();
        }
        if (other.getContentType() != 0) {
          setContentType(other.getContentType());
        }
        if (other.hasContentData()) {
          mergeContentData(other.getContentData());
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TopicMsgProto.TopicMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TopicMsgProto.TopicMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int bizSource_ ;
      /**
       * <code>int32 bizSource = 2;</code>
       */
      public int getBizSource() {
        return bizSource_;
      }
      /**
       * <code>int32 bizSource = 2;</code>
       */
      public Builder setBizSource(int value) {
        
        bizSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bizSource = 2;</code>
       */
      public Builder clearBizSource() {
        
        bizSource_ = 0;
        onChanged();
        return this;
      }

      private long topicId_ ;
      /**
       * <code>int64 topicId = 3;</code>
       */
      public long getTopicId() {
        return topicId_;
      }
      /**
       * <code>int64 topicId = 3;</code>
       */
      public Builder setTopicId(long value) {
        
        topicId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 topicId = 3;</code>
       */
      public Builder clearTopicId() {
        
        topicId_ = 0L;
        onChanged();
        return this;
      }

      private long senderId_ ;
      /**
       * <code>int64 senderId = 4;</code>
       */
      public long getSenderId() {
        return senderId_;
      }
      /**
       * <code>int64 senderId = 4;</code>
       */
      public Builder setSenderId(long value) {
        
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 senderId = 4;</code>
       */
      public Builder clearSenderId() {
        
        senderId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <code>string senderName = 5;</code>
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderName = 5;</code>
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 5;</code>
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 5;</code>
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reqId_ = "";
      /**
       * <code>string reqId = 6;</code>
       */
      public java.lang.String getReqId() {
        java.lang.Object ref = reqId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reqId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getReqIdBytes() {
        java.lang.Object ref = reqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqId = 6;</code>
       */
      public Builder setReqId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reqId = 6;</code>
       */
      public Builder clearReqId() {
        
        reqId_ = getDefaultInstance().getReqId();
        onChanged();
        return this;
      }
      /**
       * <code>string reqId = 6;</code>
       */
      public Builder setReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqId_ = value;
        onChanged();
        return this;
      }

      private int contentType_ ;
      /**
       * <code>int32 contentType = 7;</code>
       */
      public int getContentType() {
        return contentType_;
      }
      /**
       * <code>int32 contentType = 7;</code>
       */
      public Builder setContentType(int value) {
        
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 contentType = 7;</code>
       */
      public Builder clearContentType() {
        
        contentType_ = 0;
        onChanged();
        return this;
      }

      private TopicMsgProto.TopicMsg.ContentDataProto contentData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TopicMsgProto.TopicMsg.ContentDataProto, TopicMsgProto.TopicMsg.ContentDataProto.Builder, TopicMsgProto.TopicMsg.ContentDataProtoOrBuilder> contentDataBuilder_;
      /**
       * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
       */
      public boolean hasContentData() {
        return contentDataBuilder_ != null || contentData_ != null;
      }
      /**
       * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
       */
      public TopicMsgProto.TopicMsg.ContentDataProto getContentData() {
        if (contentDataBuilder_ == null) {
          return contentData_ == null ? TopicMsgProto.TopicMsg.ContentDataProto.getDefaultInstance() : contentData_;
        } else {
          return contentDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
       */
      public Builder setContentData(TopicMsgProto.TopicMsg.ContentDataProto value) {
        if (contentDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contentData_ = value;
          onChanged();
        } else {
          contentDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
       */
      public Builder setContentData(
          TopicMsgProto.TopicMsg.ContentDataProto.Builder builderForValue) {
        if (contentDataBuilder_ == null) {
          contentData_ = builderForValue.build();
          onChanged();
        } else {
          contentDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
       */
      public Builder mergeContentData(TopicMsgProto.TopicMsg.ContentDataProto value) {
        if (contentDataBuilder_ == null) {
          if (contentData_ != null) {
            contentData_ =
              TopicMsgProto.TopicMsg.ContentDataProto.newBuilder(contentData_).mergeFrom(value).buildPartial();
          } else {
            contentData_ = value;
          }
          onChanged();
        } else {
          contentDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
       */
      public Builder clearContentData() {
        if (contentDataBuilder_ == null) {
          contentData_ = null;
          onChanged();
        } else {
          contentData_ = null;
          contentDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
       */
      public TopicMsgProto.TopicMsg.ContentDataProto.Builder getContentDataBuilder() {
        
        onChanged();
        return getContentDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
       */
      public TopicMsgProto.TopicMsg.ContentDataProtoOrBuilder getContentDataOrBuilder() {
        if (contentDataBuilder_ != null) {
          return contentDataBuilder_.getMessageOrBuilder();
        } else {
          return contentData_ == null ?
              TopicMsgProto.TopicMsg.ContentDataProto.getDefaultInstance() : contentData_;
        }
      }
      /**
       * <code>.TopicMsg.ContentDataProto contentData = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TopicMsgProto.TopicMsg.ContentDataProto, TopicMsgProto.TopicMsg.ContentDataProto.Builder, TopicMsgProto.TopicMsg.ContentDataProtoOrBuilder> 
          getContentDataFieldBuilder() {
        if (contentDataBuilder_ == null) {
          contentDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TopicMsgProto.TopicMsg.ContentDataProto, TopicMsgProto.TopicMsg.ContentDataProto.Builder, TopicMsgProto.TopicMsg.ContentDataProtoOrBuilder>(
                  getContentData(),
                  getParentForChildren(),
                  isClean());
          contentData_ = null;
        }
        return contentDataBuilder_;
      }

      private long sendTime_ ;
      /**
       * <code>int64 sendTime = 9;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>int64 sendTime = 9;</code>
       */
      public Builder setSendTime(long value) {
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sendTime = 9;</code>
       */
      public Builder clearSendTime() {
        
        sendTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TopicMsg)
    }

    // @@protoc_insertion_point(class_scope:TopicMsg)
    private static final TopicMsgProto.TopicMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TopicMsgProto.TopicMsg();
    }

    public static TopicMsgProto.TopicMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopicMsg>
        PARSER = new com.google.protobuf.AbstractParser<TopicMsg>() {
      public TopicMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopicMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TopicMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopicMsg> getParserForType() {
      return PARSER;
    }

    public TopicMsgProto.TopicMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopicMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicMsg_ContentDataProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopicMsg_ContentDataProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TopicMsg.proto\"\270\002\n\010TopicMsg\022\n\n\002id\030\001 \001(" +
      "\003\022\021\n\tbizSource\030\002 \001(\005\022\017\n\007topicId\030\003 \001(\003\022\020\n" +
      "\010senderId\030\004 \001(\003\022\022\n\nsenderName\030\005 \001(\t\022\r\n\005r" +
      "eqId\030\006 \001(\t\022\023\n\013contentType\030\007 \001(\005\022/\n\013conte" +
      "ntData\030\010 \001(\0132\032.TopicMsg.ContentDataProto" +
      "\022\020\n\010sendTime\030\t \001(\003\032o\n\020ContentDataProto\022\013" +
      "\n\003msg\030\001 \001(\t\022\013\n\003rid\030\002 \001(\t\022\021\n\tthumbnail\030\003 " +
      "\001(\t\022\017\n\007viewUrl\030\004 \001(\t\022\r\n\005width\030\005 \001(\005\022\016\n\006h" +
      "eight\030\006 \001(\005B\017B\rTopicMsgProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TopicMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TopicMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopicMsg_descriptor,
        new java.lang.String[] { "Id", "BizSource", "TopicId", "SenderId", "SenderName", "ReqId", "ContentType", "ContentData", "SendTime", });
    internal_static_TopicMsg_ContentDataProto_descriptor =
      internal_static_TopicMsg_descriptor.getNestedTypes().get(0);
    internal_static_TopicMsg_ContentDataProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopicMsg_ContentDataProto_descriptor,
        new java.lang.String[] { "Msg", "Rid", "Thumbnail", "ViewUrl", "Width", "Height", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
